/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import db.DBConnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/**
 *
 * @author HOME
 */
public class ChangePassword extends javax.swing.JFrame {

    /**
     * Creates new form ChangePassword
     */
    ProfileId temp;
    String user;

    public ChangePassword() {
        initComponents();
        temp = new ProfileId();
    }

    public ChangePassword(ProfileId temp, String user) {

        initComponents();
        this.user = user;
        this.temp = temp;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        passwordPnl = new javax.swing.JPanel();
        oldpassLbl = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        confirmppassLbl = new javax.swing.JLabel();
        okBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        ppassTF = new javax.swing.JPasswordField();
        confirmppassTF = new javax.swing.JPasswordField();
        hintqLbl = new javax.swing.JLabel();
        hintqCB = new javax.swing.JComboBox();
        hintaLbl = new javax.swing.JLabel();
        hintaTF = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        passwordPnl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        oldpassLbl.setText("<html>Set Password <font color=\"red\">*</font></html>");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 153));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Profile Password");

        confirmppassLbl.setText("Confirm  Password");

        okBtn.setText("OK");
        okBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okBtnActionPerformed(evt);
            }
        });

        cancelBtn.setText("Cancel");

        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("* Different from profile password");

        hintqLbl.setText("Hint Question");

        hintqCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pet's name?", "Favourite color?" }));
        hintqCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hintqCBActionPerformed(evt);
            }
        });

        hintaLbl.setText("Answer");

        javax.swing.GroupLayout passwordPnlLayout = new javax.swing.GroupLayout(passwordPnl);
        passwordPnl.setLayout(passwordPnlLayout);
        passwordPnlLayout.setHorizontalGroup(
            passwordPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(passwordPnlLayout.createSequentialGroup()
                .addGroup(passwordPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(passwordPnlLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(okBtn)
                        .addGap(4, 4, 4)
                        .addComponent(cancelBtn))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, passwordPnlLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(passwordPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(passwordPnlLayout.createSequentialGroup()
                                .addGroup(passwordPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(hintaLbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(hintqLbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(confirmppassLbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                    .addComponent(oldpassLbl, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(passwordPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ppassTF, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                    .addComponent(confirmppassTF)
                                    .addComponent(hintqCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(hintaTF))))))
                .addContainerGap(22, Short.MAX_VALUE))
            .addGroup(passwordPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        passwordPnlLayout.setVerticalGroup(
            passwordPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(passwordPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(passwordPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ppassTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(oldpassLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(passwordPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmppassLbl)
                    .addComponent(confirmppassTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(passwordPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(hintqCB)
                    .addComponent(hintqLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(passwordPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hintaLbl)
                    .addComponent(hintaTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(passwordPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(okBtn)
                    .addComponent(cancelBtn))
                .addGap(31, 31, 31))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(passwordPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(passwordPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okBtnActionPerformed
        try {
            Connection con2 = DBConnection.getConnection();
            String query = "insert into logincheck values(?,?,?,?,?)";
            temp.setPass(ppassTF.getText(), hintqCB.getSelectedItem().toString(), hintaTF.getText());
            try (PreparedStatement psmt = con2.prepareStatement(query)) {
                psmt.setString(1, temp.loginName);
                psmt.setString(2, temp.pPass);
                psmt.setString(3, temp.lPass);
                psmt.setString(4, temp.email);
                psmt.setString(5, temp.status);
                psmt.executeUpdate();
            }
            // Connection c2 = DBConnection.getConnection();
            String query2 = "insert into profile_id values (?,?,?,?,?,?,?)";
            try (PreparedStatement psmt1 = con2.prepareStatement(query2)) {
                psmt1.setString(1, temp.loginName);
                psmt1.setString(2, temp.lPass);
                psmt1.setString(3, temp.pPass);
                psmt1.setString(4, temp.status);
                psmt1.setString(5, temp.hintQ);
                psmt1.setString(6, temp.hintA);
                psmt1.setString(7, temp.email);
                psmt1.executeUpdate();
            }
            // Connection con = DBConnection.getConnection();
            String query1 = "insert into user_session(user_id,serial_no,login)values(?,1,sysdate)";
            try (PreparedStatement psmt3 = con2.prepareStatement(query1)) {
                psmt3.setString(1, temp.loginName);

                psmt3.executeUpdate();

                //JOptionPane.showMessageDialog(this, "Added Successfully", "About Login", JOptionPane.INFORMATION_MESSAGE);
            }
            String query4 = "insert into admin values(?,?,?,?,?,?,?,?)";
            try (PreparedStatement psmt4 = con2.prepareStatement(query4)) {
                psmt4.setString(1, temp.loginName+123);
                psmt4.setString(2, temp.loginName);
                psmt4.setString(3, temp.ATM);
                psmt4.setString(4, temp.NAME);
                psmt4.setString(5, "patiala");
                psmt4.setString(6, temp.PIN);
                psmt4.setString(7, "true");
                psmt4.setString(8, "10000");
                psmt4.executeUpdate();
                JOptionPane.showMessageDialog(this, "Added in Admin", "About Admin", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
                new ProductList(user).setVisible(true);
            }

        } catch (Exception ex) {
            ex.printStackTrace();
        }

    }//GEN-LAST:event_okBtnActionPerformed

    private void hintqCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hintqCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hintqCBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChangePassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelBtn;
    private javax.swing.JLabel confirmppassLbl;
    private javax.swing.JPasswordField confirmppassTF;
    private javax.swing.JLabel hintaLbl;
    private javax.swing.JTextField hintaTF;
    private javax.swing.JComboBox hintqCB;
    private javax.swing.JLabel hintqLbl;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JButton okBtn;
    private javax.swing.JLabel oldpassLbl;
    private javax.swing.JPanel passwordPnl;
    private javax.swing.JPasswordField ppassTF;
    // End of variables declaration//GEN-END:variables
}
