/*/
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import db.DBConnection;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;

/**
 *
 * @author HOME
 */
public class LoginFrame extends javax.swing.JFrame {

    static int i = 2;
    String secuser = "raman";
    String firuser = "";

    /**
     * Creates new form LoginFrame
     */
    public LoginFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        panel1 = new java.awt.Panel();
        InternetBankJL = new javax.swing.JLabel();
        image = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        accountJL = new javax.swing.JLabel();
        accountCB = new javax.swing.JComboBox();
        usernameJL = new javax.swing.JLabel();
        usernameTF = new javax.swing.JTextField();
        passwordJL = new javax.swing.JLabel();
        passwordPF = new javax.swing.JPasswordField();
        loginBTN = new javax.swing.JButton();
        cancelBTN = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 144, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 170, Short.MAX_VALUE)
        );

        jButton1.setText("jButton1");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setText("jLabel2");

        jLabel3.setText("jLabel3");

        jLabel8.setText("jLabel8");

        jLabel11.setText("jLabel11");

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 196, Short.MAX_VALUE)
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Internet Banking");
        setBounds(new java.awt.Rectangle(200, 200, 0, 0));
        setMinimumSize(new java.awt.Dimension(600, 400));
        setPreferredSize(new java.awt.Dimension(500, 300));

        InternetBankJL.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        InternetBankJL.setForeground(new java.awt.Color(255, 0, 51));
        InternetBankJL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        InternetBankJL.setText("INTERNET BANKING");
        InternetBankJL.setPreferredSize(new java.awt.Dimension(181, 30));

        image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/internet-100016261-large.jpg"))); // NOI18N
        image.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new java.awt.GridLayout(4, 2, 5, 5));

        accountJL.setText("Account");
        jPanel1.add(accountJL);

        accountCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Admin", "Employee", "User" }));
        jPanel1.add(accountCB);

        usernameJL.setText("Username");
        jPanel1.add(usernameJL);

        usernameTF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                usernameTFFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                usernameTFFocusLost(evt);
            }
        });
        jPanel1.add(usernameTF);

        passwordJL.setText("Password");
        jPanel1.add(passwordJL);

        passwordPF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordPFFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordPFFocusLost(evt);
            }
        });
        passwordPF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passwordPFKeyPressed(evt);
            }
        });
        jPanel1.add(passwordPF);

        loginBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/login.png"))); // NOI18N
        loginBTN.setText("Login");
        loginBTN.setToolTipText("Login");
        loginBTN.setIconTextGap(10);
        loginBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBTNActionPerformed(evt);
            }
        });
        jPanel1.add(loginBTN);

        cancelBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cancel.png"))); // NOI18N
        cancelBTN.setText("Cancel");
        cancelBTN.setToolTipText("Cancel");
        cancelBTN.setIconTextGap(10);
        cancelBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBTNActionPerformed(evt);
            }
        });
        jPanel1.add(cancelBTN);

        jMenu1.setText("File");

        jMenuItem1.setText("Exit");
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Help");

        jMenuItem2.setText("About");
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(image, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(InternetBankJL, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(image, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(InternetBankJL, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usernameTFFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameTFFocusGained
        usernameTF.setBackground(Color.PINK);
    }//GEN-LAST:event_usernameTFFocusGained

    private void usernameTFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameTFFocusLost
        usernameTF.setBackground(Color.WHITE);
    }//GEN-LAST:event_usernameTFFocusLost

    private void passwordPFFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordPFFocusGained
        passwordPF.setBackground(Color.PINK);
    }//GEN-LAST:event_passwordPFFocusGained

    private void passwordPFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordPFFocusLost
        passwordPF.setBackground(Color.WHITE);
    }//GEN-LAST:event_passwordPFFocusLost

    private void loginBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBTNActionPerformed
        try {
            if (usernameTF.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please Enter UserName", "About Login", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (passwordPF.getCaretPosition() == 0) {
                JOptionPane.showMessageDialog(this, "Please Enter Password", "About Login", JOptionPane.ERROR_MESSAGE);
                return;
            }

            Connection con = DBConnection.getConnection();
            String query = "select * from logincheck where username=?";
            PreparedStatement psmt = con.prepareStatement(query);
            psmt.setString(1, usernameTF.getText());
            //psmt.setString(2, passwordPF.getText());
            ResultSet rs = psmt.executeQuery();

            if (rs.next() == true) {
                i = 2;
                if (rs.getString("status").equalsIgnoreCase("true")) {
                    if (rs.getString("lpass").equals(passwordPF.getText())) {

                        try {

                            String query2 = "select * from user_session where user_id=? and serial_no=(select max(serial_no)from user_session where user_id=?)";
                            //String query2 = "select serial_no from user_session  (select max (serial_no) from user_session where user_id=? )";
                            try (PreparedStatement psmt2 = con.prepareStatement(query2)) {
                                psmt2.setString(1, usernameTF.getText());
                                psmt2.setString(2, usernameTF.getText());
                                try (ResultSet rst = psmt2.executeQuery()) {
                                    if (rst.next()) {
                                        int serial = rst.getInt("serial_no");
                                        System.out.println(serial);
                                        String query3 = "insert into user_session (user_id,serial_no,login) values(?,?,sysdate)";
                                        try (PreparedStatement psmt3 = con.prepareStatement(query3)) {
                                            psmt3.setString(1, usernameTF.getText());
                                            psmt3.setInt(2, serial + 1);
                                            psmt3.executeQuery();

                                        }
                                    }
                                }
                            }

                        } catch (Exception ex) {
                            ex.printStackTrace();
                        }
                        JOptionPane.showMessageDialog(this, "Successfullly Logged In", "About Login", JOptionPane.INFORMATION_MESSAGE);
                        this.dispose();
                        new ProductList(usernameTF.getText()).setVisible(true);

                    } else if (i != 0) {

                        String curuser = usernameTF.getText();
                        if (curuser.equals(firuser) == false) {
                            i = 2;
                            JOptionPane.showMessageDialog(this, "Incorrect password And you have " + i + "tries left", "About Login", JOptionPane.INFORMATION_MESSAGE);
                            secuser = firuser;
                            firuser = curuser;

                        } else if (curuser.equals(firuser) && curuser.equals(secuser)) {
                            JOptionPane.showMessageDialog(this, "I locked account", "About Login", JOptionPane.INFORMATION_MESSAGE);
                            secuser = firuser;
                            firuser = curuser;
                        } else if (curuser.equals(firuser) && (curuser.equals(secuser) == false)) {
                            i = 1;
                            JOptionPane.showMessageDialog(this, "Incorrect password And you have " + i + "tries left", "About Login", JOptionPane.INFORMATION_MESSAGE);
                            secuser = firuser;
                            firuser = curuser;
                        }

                    } else {
                        JOptionPane.showMessageDialog(this, "Account Locked", "About Login", JOptionPane.INFORMATION_MESSAGE);
                    }
                    // JOptionPane.showInputDialog(this, "Please Enter Name", JOptionPane.INPUT_VALUE_PROPERTY);

                } else {
                    JOptionPane.showMessageDialog(this, "Account Locked", "About Login", JOptionPane.INFORMATION_MESSAGE);
                    this.dispose();
                    new CoverFrame().setVisible(true);
                }

            } else {
                JOptionPane.showMessageDialog(this, "Incorrect Username", "About Login", JOptionPane.INFORMATION_MESSAGE);

            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    /*
     while (rs.next()) {
     user = rs.getString("username");
     if (rs.getString("username").equalsIgnoreCase(usernameTF.getText())) {
     if (rs.getString("status").equalsIgnoreCase("true")) {
     i = checkPassword(rs.getString("lpass"), passwordPF);
     if (i == 1) {
     JOptionPane.showMessageDialog(this, "You have successfully logged in", "About login", JOptionPane.INFORMATION_MESSAGE);
     this.dispose();
     new ProductList().setVisible(true);

     } else {
     String query1 = "update logincheck set status='" + false + "'where username=" + user;
     PreparedStatement psmt = con.prepareStatement(query1);
     psmt.executeUpdate();

     this.dispose();
     new CoverFrame().setVisible(true);
     }
     } else {
     JOptionPane.showMessageDialog(this, "Your account has been locked for one day", "Account Locked", JOptionPane.INFORMATION_MESSAGE);
     }
     }
     }
     if ((i != 1) && (i != 0)) {
     JOptionPane.showMessageDialog(this, "Incorrect Username", "About Login", JOptionPane.INFORMATION_MESSAGE);
     }
     } catch (Exception ex) {
     ex.printStackTrace();
     }
    }//GEN-LAST:event_loginBTNActionPerformed
*/
    private void passwordPFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordPFKeyPressed
        try {
            if (evt.getKeyCode() == 10) {

            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_passwordPFKeyPressed

    private void cancelBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBTNActionPerformed
        usernameTF.setText("");
        passwordPF.setText("");
    }//GEN-LAST:event_cancelBTNActionPerformed
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CoverFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CoverFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CoverFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CoverFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CoverFrame().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel InternetBankJL;
    private javax.swing.JComboBox accountCB;
    private javax.swing.JLabel accountJL;
    private javax.swing.JButton cancelBTN;
    private javax.swing.JLabel image;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton loginBTN;
    private java.awt.Panel panel1;
    private javax.swing.JLabel passwordJL;
    private javax.swing.JPasswordField passwordPF;
    private javax.swing.JLabel usernameJL;
    private javax.swing.JTextField usernameTF;
    // End of variables declaration//GEN-END:variables
}
