 /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import db.DBConnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/**
 *
 * @author HOME
 */
public class ProductList extends javax.swing.JFrame {

    /**
     * Creates new form ProductList
     */
    String user;

    public ProductList() {
        initComponents();
        this.user = "raman20";
        welcomeTF.setText("Welcome " + user);
    }

    public ProductList(String user) {
        initComponents();
        this.user = user;
        welcomeTF.setText("Welcome " + user);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        productPnl = new javax.swing.JPanel();
        productslbl = new javax.swing.JLabel();
        helpBtn = new javax.swing.JButton();
        logoutBtn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        billBtn1 = new javax.swing.JButton();
        accountBtn1 = new javax.swing.JButton();
        transferFundsBtn = new javax.swing.JButton();
        accounttransBtn1 = new javax.swing.JButton();
        chequeBtn1 = new javax.swing.JButton();
        loansBtn1 = new javax.swing.JButton();
        fdBtn1 = new javax.swing.JButton();
        balanceBtn1 = new javax.swing.JButton();
        closeaccountBtn1 = new javax.swing.JButton();
        utilitiesBtn1 = new javax.swing.JButton();
        welcomeTF = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        productslbl.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        productslbl.setForeground(new java.awt.Color(0, 0, 153));
        productslbl.setText("Products And Services");

        helpBtn.setText("Help");
        helpBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpBtnActionPerformed(evt);
            }
        });

        logoutBtn.setText("Logout");
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(new java.awt.GridLayout(5, 2, 5, 5));

        billBtn1.setForeground(new java.awt.Color(0, 0, 204));
        billBtn1.setText("Bill Payment");
        jPanel3.add(billBtn1);

        accountBtn1.setForeground(new java.awt.Color(0, 0, 204));
        accountBtn1.setText("Open Account");
        accountBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountBtn1ActionPerformed(evt);
            }
        });
        jPanel3.add(accountBtn1);

        transferFundsBtn.setForeground(new java.awt.Color(0, 0, 204));
        transferFundsBtn.setText("Transfer Funds");
        transferFundsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transferFundsBtnActionPerformed(evt);
            }
        });
        jPanel3.add(transferFundsBtn);

        accounttransBtn1.setForeground(new java.awt.Color(0, 0, 204));
        accounttransBtn1.setText("View Account Transactions");
        accounttransBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accounttransBtn1ActionPerformed(evt);
            }
        });
        jPanel3.add(accounttransBtn1);

        chequeBtn1.setForeground(new java.awt.Color(0, 0, 204));
        chequeBtn1.setText("Cheque Services");
        jPanel3.add(chequeBtn1);

        loansBtn1.setForeground(new java.awt.Color(0, 0, 204));
        loansBtn1.setText("Loans");
        jPanel3.add(loansBtn1);

        fdBtn1.setForeground(new java.awt.Color(0, 0, 204));
        fdBtn1.setText("Fixed Deposits");
        jPanel3.add(fdBtn1);

        balanceBtn1.setForeground(new java.awt.Color(0, 0, 204));
        balanceBtn1.setText("Balance Enquiry");
        balanceBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                balanceBtn1ActionPerformed(evt);
            }
        });
        jPanel3.add(balanceBtn1);

        closeaccountBtn1.setForeground(new java.awt.Color(0, 0, 204));
        closeaccountBtn1.setText("Close Account");
        closeaccountBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeaccountBtn1ActionPerformed(evt);
            }
        });
        jPanel3.add(closeaccountBtn1);

        utilitiesBtn1.setForeground(new java.awt.Color(0, 0, 204));
        utilitiesBtn1.setText("Utilities");
        utilitiesBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                utilitiesBtn1ActionPerformed(evt);
            }
        });
        jPanel3.add(utilitiesBtn1);

        welcomeTF.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        welcomeTF.setForeground(new java.awt.Color(255, 153, 153));
        welcomeTF.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        welcomeTF.setText("ggg");

        javax.swing.GroupLayout productPnlLayout = new javax.swing.GroupLayout(productPnl);
        productPnl.setLayout(productPnlLayout);
        productPnlLayout.setHorizontalGroup(
            productPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(productPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(productPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, productPnlLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(helpBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(logoutBtn))
                    .addGroup(productPnlLayout.createSequentialGroup()
                        .addComponent(productslbl, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(welcomeTF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        productPnlLayout.setVerticalGroup(
            productPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(productPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(productPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(helpBtn)
                    .addComponent(logoutBtn))
                .addGap(13, 13, 13)
                .addGroup(productPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(productslbl, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(welcomeTF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(productPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(productPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void helpBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpBtnActionPerformed
        this.dispose();
        new Help(this, user).setVisible(true);
    }//GEN-LAST:event_helpBtnActionPerformed

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        try {
            Connection con = DBConnection.getConnection();
            String query = "update user_session set logout=sysdate where user_id=? and logout is null ";
            PreparedStatement psmt1 = con.prepareStatement(query);

            psmt1.setString(1, user);

            psmt1.executeUpdate();
            JOptionPane.showMessageDialog(this, "Successfully logout", "About logout", JOptionPane.INFORMATION_MESSAGE);

        } catch (Exception ex) {
            ex.printStackTrace();
        }
        this.dispose();
        new CoverFrame().setVisible(true);
    }//GEN-LAST:event_logoutBtnActionPerformed

    private void accountBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountBtn1ActionPerformed
        //this.dispose();
        // new UserRegistration(this).setVisible(true);
    }//GEN-LAST:event_accountBtn1ActionPerformed

    private void utilitiesBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_utilitiesBtn1ActionPerformed
        this.dispose();
        new Utilities(user).setVisible(true);
    }//GEN-LAST:event_utilitiesBtn1ActionPerformed

    private void accounttransBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accounttransBtn1ActionPerformed
        this.dispose();
        new Transactions(user).setVisible(true);
    }//GEN-LAST:event_accounttransBtn1ActionPerformed

    private void balanceBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_balanceBtn1ActionPerformed
        this.dispose();
        new Balance(user).setVisible(true);
    }//GEN-LAST:event_balanceBtn1ActionPerformed

    private void closeaccountBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeaccountBtn1ActionPerformed
        this.dispose();
        new CloseAcc(user).setVisible(true);
    }//GEN-LAST:event_closeaccountBtn1ActionPerformed

    private void transferFundsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transferFundsBtnActionPerformed
        this.dispose();
        new TransferFunds(user).setVisible(true);
    }//GEN-LAST:event_transferFundsBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProductList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProductList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProductList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProductList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProductList().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton accountBtn1;
    private javax.swing.JButton accounttransBtn1;
    private javax.swing.JButton balanceBtn1;
    private javax.swing.JButton billBtn1;
    private javax.swing.JButton chequeBtn1;
    private javax.swing.JButton closeaccountBtn1;
    private javax.swing.JButton fdBtn1;
    private javax.swing.JButton helpBtn;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton loansBtn1;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JPanel productPnl;
    private javax.swing.JLabel productslbl;
    private javax.swing.JButton transferFundsBtn;
    private javax.swing.JButton utilitiesBtn1;
    private javax.swing.JLabel welcomeTF;
    // End of variables declaration//GEN-END:variables
}
