/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import core.ResizeImage;
import db.DBConnection;
import java.io.File;
import java.io.FileInputStream;
import java.sql.*;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author HOME
 */
public class ProfileFrame extends javax.swing.JFrame {

    /**
     * Creates new form ProfileFrame
     */
    ProfileId q;
    String user;
    File file;

    public ProfileFrame(ProfileId q, String user) {
        initComponents();
        jProgressBar1.setValue(60);
        this.q = q;
        this.user = user;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jFileChooser1 = new javax.swing.JFileChooser();
        starTF = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        profileTF = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jProgressBar1 = new javax.swing.JProgressBar();
        imageLbl = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        profilePnl = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        nameTF = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        addressTF = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cityTF = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        postalTF = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        countryTF = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        homephoneTF = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        workphoneTF = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        mobileTF = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        submitBtn = new javax.swing.JButton();
        clearBtn = new javax.swing.JButton();
        emailLbl = new javax.swing.JLabel();
        emailTF = new javax.swing.JTextField();

        starTF.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        starTF.setForeground(new java.awt.Color(255, 0, 51));
        starTF.setText("*");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login Frame");
        setMinimumSize(new java.awt.Dimension(500, 400));

        profileTF.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        profileTF.setForeground(new java.awt.Color(0, 153, 153));
        profileTF.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        profileTF.setText("PROFILE");

        imageLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imageLbl.setText("Upload Image");
        imageLbl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        imageLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imageLblMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(imageLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(imageLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        profilePnl.setLayout(new java.awt.GridLayout(8, 2, 5, 5));

        jLabel2.setText("<html><body>Name<font color=\"red\"> *</font></body></html>");
        profilePnl.add(jLabel2);
        profilePnl.add(nameTF);

        jLabel3.setText("Address");
        profilePnl.add(jLabel3);
        profilePnl.add(addressTF);

        jLabel4.setText("City");
        profilePnl.add(jLabel4);
        profilePnl.add(cityTF);

        jLabel5.setText("Postal Code");
        profilePnl.add(jLabel5);
        profilePnl.add(postalTF);

        jLabel6.setText("Country");
        profilePnl.add(jLabel6);
        profilePnl.add(countryTF);

        jLabel7.setText("Home Phone Number");
        profilePnl.add(jLabel7);
        profilePnl.add(homephoneTF);

        jLabel8.setText("Work Phone NUmber");
        profilePnl.add(jLabel8);
        profilePnl.add(workphoneTF);

        jLabel9.setText("Mobile Phone NUmber");
        profilePnl.add(jLabel9);
        profilePnl.add(mobileTF);

        jLabel11.setForeground(new java.awt.Color(255, 0, 51));
        jLabel11.setText("* Required Fields");

        submitBtn.setText("Submit");
        submitBtn.setToolTipText("Submit");
        submitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBtnActionPerformed(evt);
            }
        });

        clearBtn.setText("Clear");
        clearBtn.setToolTipText("Clear");
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });

        emailLbl.setText("E-Mail");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                        .addComponent(submitBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(clearBtn))
                    .addComponent(profilePnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(emailLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(emailTF)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(profilePnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailLbl)
                    .addComponent(emailTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(submitBtn)
                        .addComponent(clearBtn))
                    .addComponent(jLabel11))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(profileTF, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(profileTF)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        nameTF.setText("");
        addressTF.setText("");
        cityTF.setText("");
        postalTF.setText("");
        homephoneTF.setText("");
        countryTF.setText("");
        workphoneTF.setText("");
        mobileTF.setText("");
    }//GEN-LAST:event_clearBtnActionPerformed

    private void submitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBtnActionPerformed
        try {
            if (nameTF.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "enter name", "about name", JOptionPane.INFORMATION_MESSAGE);
                return;
            }

            Connection c2 = DBConnection.getConnection();
            String query = "insert into profile values(?,?,?,?,?,?,?,?,?,?,?)";
            PreparedStatement psmt = c2.prepareStatement(query);
            psmt.setString(1, nameTF.getText());
            psmt.setString(2, addressTF.getText());
            psmt.setString(3, cityTF.getText());
            psmt.setString(5, countryTF.getText());
            psmt.setString(4, postalTF.getText());
            psmt.setString(6, homephoneTF.getText());
            psmt.setString(7, workphoneTF.getText());
            psmt.setString(8, mobileTF.getText());
            FileInputStream fin = new FileInputStream(file);
            psmt.setBinaryStream(9, fin, fin.available());
            //psmt.setString(9, "");
            psmt.setString(10, emailTF.getText());
            psmt.setString(11, user);
            q.setP(emailTF.getText(), nameTF.getText());

            if (psmt.executeUpdate() == 1) {
                jProgressBar1.setValue(100);
                JOptionPane.showMessageDialog(this, "You have successfully logged in", "About Login", JOptionPane.INFORMATION_MESSAGE);

                nameTF.setText("");
                addressTF.setText("");
                cityTF.setText("");
                postalTF.setText("");
                homephoneTF.setText("");
                countryTF.setText("");
                workphoneTF.setText("");
                mobileTF.setText("");
                emailTF.setText("");

                psmt.close();
                //c2.close();
                this.dispose();
                new ChangePassword(q, user).setVisible(true);

            } else {
                JOptionPane.showMessageDialog(this, "ERROR : ", "About Login", JOptionPane.ERROR_MESSAGE);
            }

            //q.setP(emailTF.getText());
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_submitBtnActionPerformed

    private void imageLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imageLblMouseClicked
        try {
            int result = jFileChooser1.showOpenDialog(this);
            if (result == JFileChooser.APPROVE_OPTION) {
                file = jFileChooser1.getSelectedFile();
                setPath(file);

            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_imageLblMouseClicked

    private void setPath(File file) {
        try {
            ImageIcon icon = ResizeImage.scaleTo(file, imageLbl.getSize());

            if (icon != null) {
                imageLbl.setText("");
                imageLbl.setIcon(icon);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressTF;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField cityTF;
    private javax.swing.JButton clearBtn;
    private javax.swing.JTextField countryTF;
    private javax.swing.JLabel emailLbl;
    private javax.swing.JTextField emailTF;
    private javax.swing.JTextField homephoneTF;
    private javax.swing.JLabel imageLbl;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JTextField mobileTF;
    private javax.swing.JTextField nameTF;
    private javax.swing.JTextField postalTF;
    private javax.swing.JPanel profilePnl;
    private javax.swing.JLabel profileTF;
    private javax.swing.JLabel starTF;
    private javax.swing.JButton submitBtn;
    private javax.swing.JTextField workphoneTF;
    // End of variables declaration//GEN-END:variables
}
