/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import db.DBConnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HOME
 */
public class TransferFunds extends javax.swing.JFrame {

    String user;
    DefaultTableModel dtm;
    Connection con;
    String query;
    PreparedStatement psmt;
    Statement stm;
    ResultSet rs2;
    JPanel aa;

    public TransferFunds() {

        initComponents();

        user = "raman20";
        welcomeLbl.setText("Welcome " + user);
        dtm = new DefaultTableModel();
        con = DBConnection.getConnection();
        aa = onetransferPnl;

        try {
            query = "select account_no from user_account where user_id='" + user + "'";
            stm = con.createStatement();
            ResultSet rrs = stm.executeQuery(query);

            DefaultComboBoxModel model = (DefaultComboBoxModel) otmDebitCB.getModel();

            // oneDebitCB.removeAllItems();
            while (rrs.next()) {
                String acc = rrs.getString("account_no");

                model.addElement(acc);

            }
            otmDebitCB.setModel(model);

        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    public TransferFunds(String username) {
        initComponents();

        user = username;
        welcomeLbl.setText("Welcome " + user);
        dtm = new DefaultTableModel();
        con = DBConnection.getConnection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        oneToManyTransPnl = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        creditTF = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        addAccBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        submitBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        amountTF = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        otmDebitCB = new javax.swing.JComboBox();
        jLabel16 = new javax.swing.JLabel();
        otmDebitBalanceTF = new javax.swing.JLabel();
        onetransferPnl = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        oneDebitCB = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tAmountTF = new javax.swing.JTextField();
        verifyTransferBtn = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        oneDebitBranchTF = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        pPassTF = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        oneCreditBalanceTF = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        oneDebitBalanceTF = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        oneCreditBranchLbl = new javax.swing.JLabel();
        oneCreditCB = new javax.swing.JComboBox();
        jPanel4 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        welcomeLbl = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel2 = new javax.swing.JPanel();
        statusBtn = new javax.swing.JButton();
        sTransferBtn = new javax.swing.JButton();
        tpTransfer = new javax.swing.JButton();
        otmTransfer = new javax.swing.JButton();
        productBtn = new javax.swing.JButton();
        logoutBtn = new javax.swing.JButton();
        helpBtn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();

        oneToManyTransPnl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 204, 153));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("ONE TO MANY TRANSFERS");

        jLabel2.setText("Credit Account");

        jLabel3.setText("Debit Account");

        addAccBtn.setText("ADD ACCOUNT");
        addAccBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAccBtnActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Credit Account", "Debit Account", "Amount"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        submitBtn.setText("Submit");
        submitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBtnActionPerformed(evt);
            }
        });

        jLabel4.setText("Amount");

        jButton1.setText("Clear");

        otmDebitCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                otmDebitCBActionPerformed(evt);
            }
        });

        jLabel16.setText("Balance");

        javax.swing.GroupLayout oneToManyTransPnlLayout = new javax.swing.GroupLayout(oneToManyTransPnl);
        oneToManyTransPnl.setLayout(oneToManyTransPnlLayout);
        oneToManyTransPnlLayout.setHorizontalGroup(
            oneToManyTransPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(oneToManyTransPnlLayout.createSequentialGroup()
                .addGroup(oneToManyTransPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(oneToManyTransPnlLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(oneToManyTransPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(oneToManyTransPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(creditTF, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                            .addComponent(amountTF))
                        .addGap(27, 27, 27)
                        .addGroup(oneToManyTransPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(oneToManyTransPnlLayout.createSequentialGroup()
                                .addComponent(addAccBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(oneToManyTransPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(otmDebitCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(otmDebitBalanceTF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(oneToManyTransPnlLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(oneToManyTransPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(oneToManyTransPnlLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(submitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, oneToManyTransPnlLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(113, 113, 113))
        );
        oneToManyTransPnlLayout.setVerticalGroup(
            oneToManyTransPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(oneToManyTransPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(oneToManyTransPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(creditTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(otmDebitCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(oneToManyTransPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(amountTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addAccBtn)
                    .addComponent(jLabel16)
                    .addComponent(otmDebitBalanceTF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(oneToManyTransPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submitBtn)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        onetransferPnl.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 204, 153));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("SIMPLE TRANSFERS");

        jLabel7.setText("Debit Account");

        oneDebitCB.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                oneDebitCBItemStateChanged(evt);
            }
        });
        oneDebitCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneDebitCBActionPerformed(evt);
            }
        });

        jLabel8.setText("Credit Account");

        jLabel9.setText("Transfer Amount");

        tAmountTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tAmountTFActionPerformed(evt);
            }
        });

        verifyTransferBtn.setText("Verify Transfer");
        verifyTransferBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verifyTransferBtnActionPerformed(evt);
            }
        });

        jLabel10.setText("Debit Branch");

        oneDebitBranchTF.setEditable(false);
        oneDebitBranchTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneDebitBranchTFActionPerformed(evt);
            }
        });

        jLabel11.setText("Profile Password");

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("* All Fields are compulsory");

        jLabel13.setText(" Balance in credit Acc:");

        oneCreditBalanceTF.setEditable(false);

        jLabel14.setText("Balance in debit Acc:");

        oneDebitBalanceTF.setEditable(false);

        jLabel15.setText("Credit Branch");

        oneCreditCB.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                oneCreditCBItemStateChanged(evt);
            }
        });
        oneCreditCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneCreditCBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout onetransferPnlLayout = new javax.swing.GroupLayout(onetransferPnl);
        onetransferPnl.setLayout(onetransferPnlLayout);
        onetransferPnlLayout.setHorizontalGroup(
            onetransferPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(onetransferPnlLayout.createSequentialGroup()
                .addGroup(onetransferPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, onetransferPnlLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(verifyTransferBtn))
                    .addGroup(onetransferPnlLayout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(onetransferPnlLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(onetransferPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(36, 36, 36)
                        .addGroup(onetransferPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(oneDebitCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(onetransferPnlLayout.createSequentialGroup()
                                .addGroup(onetransferPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(onetransferPnlLayout.createSequentialGroup()
                                        .addComponent(tAmountTF, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(onetransferPnlLayout.createSequentialGroup()
                                        .addComponent(pPassTF, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel13)
                                        .addGap(0, 6, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(onetransferPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(oneCreditBalanceTF, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                                    .addComponent(oneDebitBalanceTF)))
                            .addGroup(onetransferPnlLayout.createSequentialGroup()
                                .addComponent(oneDebitBranchTF, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(oneCreditBranchLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(oneCreditCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        onetransferPnlLayout.setVerticalGroup(
            onetransferPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(onetransferPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(onetransferPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(oneDebitCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(onetransferPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(oneCreditCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(onetransferPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(oneCreditBranchLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(onetransferPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(oneDebitBranchTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel15)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(onetransferPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tAmountTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(oneDebitBalanceTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(onetransferPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(pPassTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(oneCreditBalanceTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(onetransferPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(verifyTransferBtn)
                    .addComponent(jLabel12))
                .addGap(19, 19, 19))
        );

        jRadioButton1.setText("jRadioButton1");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(215, 215, 215)
                .addComponent(jRadioButton1)
                .addContainerGap(259, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jRadioButton1)
                .addContainerGap(249, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Transfer Funds");

        welcomeLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        welcomeLbl.setText("ggg");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jSplitPane1.setDividerLocation(160);

        statusBtn.setText("Status");

        sTransferBtn.setText("Simple Transfer");
        sTransferBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sTransferBtnActionPerformed(evt);
            }
        });

        tpTransfer.setText("Third Party Transfer");
        tpTransfer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tpTransferActionPerformed(evt);
            }
        });

        otmTransfer.setText("One To Many Transfer");
        otmTransfer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                otmTransferActionPerformed(evt);
            }
        });

        productBtn.setText("Products And Services");
        productBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productBtnActionPerformed(evt);
            }
        });

        logoutBtn.setText("Logout");
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });

        helpBtn.setText("Help");
        helpBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(statusBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sTransferBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tpTransfer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(otmTransfer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(helpBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(logoutBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(productBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(statusBtn)
                .addGap(9, 9, 9)
                .addComponent(sTransferBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tpTransfer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(otmTransfer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addComponent(helpBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logoutBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(productBtn)
                .addContainerGap())
        );

        jSplitPane1.setLeftComponent(jPanel2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 497, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 283, Short.MAX_VALUE)
        );

        jSplitPane1.setRightComponent(jPanel3);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(welcomeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(welcomeLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void helpBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpBtnActionPerformed
        this.dispose();
        new Help(this, user).setVisible(true);
    }//GEN-LAST:event_helpBtnActionPerformed

    private void productBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productBtnActionPerformed
        this.dispose();
        new ProductList(user).setVisible(true);
    }//GEN-LAST:event_productBtnActionPerformed

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        try {

            query = "update user_session set logout=sysdate where user_id=? and logout is null ";
            psmt = con.prepareStatement(query);
            psmt.setString(1, user);
            psmt.executeUpdate();
            JOptionPane.showMessageDialog(this, "Successfully logout", "About logout", JOptionPane.INFORMATION_MESSAGE);

        } catch (Exception ex) {
            ex.printStackTrace();
        }
        this.dispose();
        new CoverFrame().setVisible(true);
    }//GEN-LAST:event_logoutBtnActionPerformed

    private void sTransferBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sTransferBtnActionPerformed

        try {
            query = "select account_no from user_account where user_id='" + user + "'";
            stm = con.createStatement();
            ResultSet rrs = stm.executeQuery(query);

            DefaultComboBoxModel model = (DefaultComboBoxModel) oneDebitCB.getModel();
            DefaultComboBoxModel model2 = (DefaultComboBoxModel) oneCreditCB.getModel();
            // oneDebitCB.removeAllItems();
            while (rrs.next()) {
                String acc = rrs.getString("account_no");

                model.addElement(acc);
                model2.addElement(acc);
            }
            oneDebitCB.setModel(model);
            oneCreditCB.setModel(model2);
            rrs.close();
            stm.close();

            jSplitPane1.setRightComponent(aa);

        } catch (Exception ex) {
            ex.printStackTrace();
        }

    }//GEN-LAST:event_sTransferBtnActionPerformed

    private void addAccBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAccBtnActionPerformed

        Vector coloumn = new Vector();
        coloumn.addElement("Credit Account");
        coloumn.addElement("Debit Account");
        coloumn.addElement("Amount");
        dtm.setColumnIdentifiers(coloumn);

        Vector row = new Vector();

        row.addElement(creditTF.getText());
        row.addElement(otmDebitCB.getSelectedItem().toString());
        row.addElement(amountTF.getText());

        dtm.addRow(row);
        jTable1.setModel(dtm);
        creditTF.setText("");

        amountTF.setText("");
    }//GEN-LAST:event_addAccBtnActionPerformed

    private void submitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBtnActionPerformed
        try {
            int row = jTable1.getRowCount();
            int col = jTable1.getColumnCount();
            for (int i = 0; i < row; i++) {
                int j = 0;
                while (j < col) {

                    /* get balance earlier of credit account*/ int pdbalance = Integer.parseInt((String) jTable1.getValueAt(i, j));
                    int pcbalance = Integer.parseInt((String) jTable1.getValueAt(i, ++j));
                    int transamount = Integer.parseInt((String) jTable1.getValueAt(i, ++j));

                    String ndbalance = String.valueOf(pdbalance - transamount);
                    String ncbalance = String.valueOf(pcbalance + transamount);
                    query = "update admin set balance='" + ndbalance + "' where account_no='" + (String) jTable1.getValueAt(i, ++j) + "'";
                    psmt = con.prepareStatement(query);
                    psmt.executeUpdate();

                    query = "update admin set balance='" + ncbalance + "' where account_no='" + oneCreditCB.getSelectedItem().toString() + "'";
                    psmt = con.prepareStatement(query);
                    psmt.executeUpdate();
                    System.out.println(transamount);
                    System.out.println(ndbalance);
                    System.out.println(ncbalance);
                }

            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_submitBtnActionPerformed

    private void otmTransferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_otmTransferActionPerformed

        jSplitPane1.setRightComponent(oneToManyTransPnl);
        oneToManyTransPnl.setVisible(true);


    }//GEN-LAST:event_otmTransferActionPerformed

    private void verifyTransferBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verifyTransferBtnActionPerformed
        try {

            query = "select ppass from profile_id where user_id='" + user + "'";
            psmt = con.prepareStatement(query);
            rs2 = psmt.executeQuery();
            if (rs2.next()) {
                if (rs2.getString("ppass").equalsIgnoreCase(pPassTF.getText())) {
                    System.out.println("correct");
                    if (!oneDebitCB.getSelectedItem().toString().equals(oneCreditCB.getSelectedItem().toString())) {
                        int pdbalance = Integer.parseInt(oneDebitBalanceTF.getText());
                        int pcbalance = Integer.parseInt(oneCreditBalanceTF.getText());
                        int transamount = Integer.parseInt(tAmountTF.getText());

                        String ndbalance = String.valueOf(pdbalance - transamount);
                        String ncbalance = String.valueOf(pcbalance + transamount);
                        query = "update admin set balance='" + ndbalance + "' where account_no='" + oneDebitCB.getSelectedItem().toString() + "'";
                        psmt = con.prepareStatement(query);
                        psmt.executeUpdate();

                        query = "update admin set balance='" + ncbalance + "' where account_no='" + oneCreditCB.getSelectedItem().toString() + "'";
                        psmt = con.prepareStatement(query);
                        psmt.executeUpdate();
                        System.out.println(transamount);
                        System.out.println(ndbalance);
                        System.out.println(ncbalance);
                        JOptionPane.showMessageDialog(this, "admin updated");

                        /* query="insert into user_transactions values(?,?,?)";
                         psmt=con.prepareStatement(query);
                         psmt.setString(1,"account_no");
                         */
                    } else {
                        JOptionPane.showMessageDialog(this, "Cannot transfer in same account");
                        return;
                    }
                } else {
                    System.out.println("wrong");
                    JOptionPane.showMessageDialog(this, "Wrong Profile Password",
                            "About Transfer", JOptionPane.INFORMATION_MESSAGE);
                    return;
                }
            }
            jSplitPane1.setRightComponent(jPanel4);
            jPanel4.setVisible(true);

        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_verifyTransferBtnActionPerformed

    private void tAmountTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tAmountTFActionPerformed
//
    }//GEN-LAST:event_tAmountTFActionPerformed

    private void oneDebitBranchTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oneDebitBranchTFActionPerformed
//
    }//GEN-LAST:event_oneDebitBranchTFActionPerformed

    private void oneDebitCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oneDebitCBActionPerformed
        try {

            query = "select * from admin where account_no='" + oneDebitCB.getSelectedItem().toString() + "' ";
            psmt = con.prepareStatement(query);
            rs2 = psmt.executeQuery();

            while (rs2.next()) {
                oneDebitBranchTF.setText(rs2.getString("branch"));
                oneDebitBalanceTF.setText(rs2.getString("balance"));
            }

        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_oneDebitCBActionPerformed

    private void oneDebitCBItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_oneDebitCBItemStateChanged


    }//GEN-LAST:event_oneDebitCBItemStateChanged

    private void oneCreditCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oneCreditCBActionPerformed
        try {
            query = "select * from admin where account_no='" + oneCreditCB.getSelectedItem().toString() + "' ";
            psmt = con.prepareStatement(query);
            rs2 = psmt.executeQuery();

            while (rs2.next()) {
                oneCreditBranchLbl.setText(rs2.getString("branch"));
                oneCreditBalanceTF.setText(rs2.getString("balance"));
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_oneCreditCBActionPerformed

    private void tpTransferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tpTransferActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tpTransferActionPerformed

    private void oneCreditCBItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_oneCreditCBItemStateChanged


    }//GEN-LAST:event_oneCreditCBItemStateChanged

    private void otmDebitCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_otmDebitCBActionPerformed
        try {
            query = "select * from admin where account_no='" + otmDebitCB.getSelectedItem().toString() + "' ";
            psmt = con.prepareStatement(query);
            rs2 = psmt.executeQuery();

            while (rs2.next()) {
                otmDebitBalanceTF.setText(rs2.getString("balance"));

            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_otmDebitCBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TransferFunds.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TransferFunds.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TransferFunds.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TransferFunds.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TransferFunds().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addAccBtn;
    private javax.swing.JTextField amountTF;
    private javax.swing.JTextField creditTF;
    private javax.swing.JButton helpBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JTextField oneCreditBalanceTF;
    private javax.swing.JLabel oneCreditBranchLbl;
    private javax.swing.JComboBox oneCreditCB;
    private javax.swing.JTextField oneDebitBalanceTF;
    private javax.swing.JTextField oneDebitBranchTF;
    private javax.swing.JComboBox oneDebitCB;
    private javax.swing.JPanel oneToManyTransPnl;
    private javax.swing.JPanel onetransferPnl;
    private javax.swing.JLabel otmDebitBalanceTF;
    private javax.swing.JComboBox otmDebitCB;
    private javax.swing.JButton otmTransfer;
    private javax.swing.JTextField pPassTF;
    private javax.swing.JButton productBtn;
    private javax.swing.JButton sTransferBtn;
    private javax.swing.JButton statusBtn;
    private javax.swing.JButton submitBtn;
    private javax.swing.JTextField tAmountTF;
    private javax.swing.JButton tpTransfer;
    private javax.swing.JButton verifyTransferBtn;
    private javax.swing.JLabel welcomeLbl;
    // End of variables declaration//GEN-END:variables
}
