/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import db.DBConnection;
import java.io.FileReader;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author HOME
 */
public class UserRegistration extends javax.swing.JFrame {

    /**
     * Creates new form UserRegistration
     */
    ProfileId p;

    public UserRegistration() {

        initComponents();

        jProgressBar1.setValue(30);
        p = new ProfileId();

        try {

            try (FileReader fr = new FileReader("terms.txt")) {
                char ch[] = new char[100];

                while ((fr.read(ch)) != -1) {
                    termsTA.append(new String(ch));
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

        termsTA.setCaretPosition(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        atmTF = new javax.swing.JTextField();
        atmLbl = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pinTF = new javax.swing.JTextField();
        pinLbl = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        useridTF = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        passwordTF = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        confirmpasswordTF = new javax.swing.JPasswordField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        agreeRB = new javax.swing.JRadioButton();
        declineRB = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        clearBTN = new javax.swing.JButton();
        submitBTN = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        termsSP = new javax.swing.JScrollPane();
        termsTA = new javax.swing.JTextArea();
        jProgressBar1 = new javax.swing.JProgressBar();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("First Time Registration");

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(new java.awt.GridLayout(5, 3, 5, 5));

        jLabel1.setText("ATM Card");
        jPanel3.add(jLabel1);
        jPanel3.add(atmTF);

        atmLbl.setForeground(new java.awt.Color(255, 0, 51));
        atmLbl.setText("*");
        jPanel3.add(atmLbl);

        jLabel2.setText("PIN");
        jPanel3.add(jLabel2);
        jPanel3.add(pinTF);

        pinLbl.setForeground(new java.awt.Color(255, 0, 51));
        pinLbl.setText("*");
        jPanel3.add(pinLbl);

        jLabel4.setText("User ID");
        jPanel3.add(jLabel4);
        jPanel3.add(useridTF);

        jLabel5.setText("<html> <body> <font color = \"red\">*</font> Minimum of 6 characters </body> </html>");
        jPanel3.add(jLabel5);

        jLabel7.setText("Password");
        jPanel3.add(jLabel7);
        jPanel3.add(passwordTF);

        jLabel8.setText("<html>\n<body>\n<font color=\"red\">*</font> password tips\n</body>\n</html>");
        jPanel3.add(jLabel8);

        jLabel9.setText("Confirm Password");
        jPanel3.add(jLabel9);
        jPanel3.add(confirmpasswordTF);

        jLabel10.setText("<html>\n<body>\n<font color=\"red\">* </font>retype the above password\n</body>\n</html>");
        jLabel10.setToolTipText("");
        jPanel3.add(jLabel10);

        jLabel11.setText("Terms and Conditions");

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        buttonGroup1.add(agreeRB);
        agreeRB.setText("Agree");

        buttonGroup1.add(declineRB);
        declineRB.setText("Decline");

        jLabel12.setText("By clicking on the \"Agree\" space above you are stating that you agree and accept to be bound by ");

        clearBTN.setText("Clear");
        clearBTN.setToolTipText("Clear");
        clearBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBTNActionPerformed(evt);
            }
        });

        submitBTN.setText("Submit");
        submitBTN.setToolTipText("Submit");
        submitBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBTNActionPerformed(evt);
            }
        });

        jLabel13.setForeground(new java.awt.Color(255, 0, 51));
        jLabel13.setText("* Required Fields");

        jLabel14.setText("all the terms and conditions aforementioned");

        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 99, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(submitBTN)
                        .addGap(5, 5, 5)
                        .addComponent(backBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(clearBTN)
                        .addGap(28, 28, 28))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(agreeRB)
                                .addGap(44, 44, 44)
                                .addComponent(declineRB))
                            .addComponent(jLabel14))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(agreeRB)
                    .addComponent(declineRB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(submitBTN)
                    .addComponent(clearBTN)
                    .addComponent(backBtn))
                .addGap(19, 19, 19))
        );

        jLabel15.setText("Please enter your ATM along with your PIN,UserID and password to register.");

        jLabel16.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 204, 153));
        jLabel16.setText("First Time Registration");

        termsTA.setEditable(false);
        termsTA.setColumns(20);
        termsTA.setLineWrap(true);
        termsTA.setRows(5);
        termsSP.setViewportView(termsTA);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(termsSP, javax.swing.GroupLayout.PREFERRED_SIZE, 586, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel11)
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(0, 0, Short.MAX_VALUE))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel15)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(termsSP, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clearBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBTNActionPerformed
        atmTF.setText("");
        pinTF.setText("");
        useridTF.setText("");
        passwordTF.setText("");
        confirmpasswordTF.setText("");
        buttonGroup1.clearSelection();

    }//GEN-LAST:event_clearBTNActionPerformed

    private void submitBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBTNActionPerformed
        try {
            if (declineRB.isSelected()) {
                atmTF.setText("");
                pinTF.setText("");
                useridTF.setText("");
                passwordTF.setText("");
                confirmpasswordTF.setText("");
                buttonGroup1.clearSelection();
                return;
            }
            if (atmTF.getText().isEmpty()) {
                atmLbl.setText("Please Enter Card Number");
                return;
            }
            if (pinTF.getText().isEmpty()) {
                pinLbl.setText("Enter PIN");
                return;
            }
            if (passwordTF.getText().equals(confirmpasswordTF.getText()) == false) {
                JOptionPane.showMessageDialog(this, "Please Enter same Password", "Confirm Password", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (useridTF.getText().length() < 6) {
                JOptionPane.showMessageDialog(this, "Enter 6 character ID", "About ID", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (passwordTF.getCaretPosition() == 0) {
                JOptionPane.showMessageDialog(this, "Please Enter Password", "About Login", JOptionPane.ERROR_MESSAGE);
                return;
            }
            ResultSet rs;
            Connection c2 = DBConnection.getConnection();
            String query1 = "select *from logincheck where username=?";
            PreparedStatement psmt1 = c2.prepareStatement(query1);
            psmt1.setString(1, useridTF.getText());
            rs = psmt1.executeQuery();
            if (rs.next() == false) {

                if (agreeRB.isSelected()) {

                    p.setURF(useridTF.getText(), passwordTF.getText());
                    p.setAtm(atmTF.getText(),pinTF.getText());
                    rs.close();
                    psmt1.close();

                    this.dispose();
                    new ProfileFrame(p, useridTF.getText()).setVisible(true);

                }
            } else {
                JOptionPane.showMessageDialog(this, "Usernmae Already Existing", "About Username", JOptionPane.INFORMATION_MESSAGE);
                return;
            }

        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_submitBTNActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        //this.dispose();
        //jframe.setVisible(true);
    }//GEN-LAST:event_backBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserRegistration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton agreeRB;
    private javax.swing.JLabel atmLbl;
    private javax.swing.JTextField atmTF;
    private javax.swing.JButton backBtn;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton clearBTN;
    private javax.swing.JPasswordField confirmpasswordTF;
    private javax.swing.JRadioButton declineRB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JPasswordField passwordTF;
    private javax.swing.JLabel pinLbl;
    private javax.swing.JTextField pinTF;
    private javax.swing.JButton submitBTN;
    private javax.swing.JScrollPane termsSP;
    private javax.swing.JTextArea termsTA;
    private javax.swing.JTextField useridTF;
    // End of variables declaration//GEN-END:variables
}
