/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import core.ResizeImage;
import db.DBConnection;
import java.awt.Dimension;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.sql.Blob;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.Statement;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HOME
 */
public class Utilities extends javax.swing.JFrame {

    String user;
    String descript;
    File file;

    public Utilities() {

        initComponents();

        user = "raman20";
        jSplitPane1.setRightComponent(passwordPnl);
        passwordPnl.setVisible(true);
        welcomeTF.setText("Welcome " + user);
    }

    public Utilities(String user) {
        initComponents();

        this.user = user;
        jSplitPane1.setRightComponent(passwordPnl);
        passwordPnl.setVisible(true);
        welcomeTF.setText("Welcome " + user);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        passwordPnl = new javax.swing.JPanel();
        oldpassLbl = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        newpassLbl = new javax.swing.JLabel();
        confirmpassLbl = new javax.swing.JLabel();
        okBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        oldPassPF = new javax.swing.JPasswordField();
        newPassTF = new javax.swing.JPasswordField();
        confPassTF = new javax.swing.JPasswordField();
        oldPassLbl = new javax.swing.JLabel();
        confirmnPassLbl = new javax.swing.JLabel();
        productPnl = new javax.swing.JPanel();
        productslbl = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        billBtn1 = new javax.swing.JButton();
        accountBtn1 = new javax.swing.JButton();
        fundsBtn1 = new javax.swing.JButton();
        accounttransBtn1 = new javax.swing.JButton();
        chequeBtn1 = new javax.swing.JButton();
        loansBtn1 = new javax.swing.JButton();
        fdBtn1 = new javax.swing.JButton();
        balanceBtn1 = new javax.swing.JButton();
        closeaccountBtn1 = new javax.swing.JButton();
        utilitiesBtn1 = new javax.swing.JButton();
        profileuserPnl = new javax.swing.JPanel();
        profilePnl = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        nameTF = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        addressTF = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cityTF = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        postalTF = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        countryTF = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        homephoneTF = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        workphoneTF = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        mobileTF = new javax.swing.JTextField();
        displayImgLbl = new javax.swing.JLabel();
        changePicLbl = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        submitBtn = new javax.swing.JButton();
        clearBtn = new javax.swing.JButton();
        emailLbl = new javax.swing.JLabel();
        emailTF = new javax.swing.JTextField();
        SessionTable = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        accProfile = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        accBranchTF = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        accTypeTF = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        descriptionTF = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox();
        cancelBtn1 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        addAccBtn = new javax.swing.JButton();
        jFileChooser1 = new javax.swing.JFileChooser();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        profileupdateBtn = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        SessionBtn = new javax.swing.JButton();
        productBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        welcomeTF = new javax.swing.JLabel();

        passwordPnl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        oldpassLbl.setText("Old Password");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 153));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Change Password");

        newpassLbl.setText("New Password");

        confirmpassLbl.setText("<html><body>Confirm Passsword<font color=\"red\"> *</font></body></html>");

        okBtn.setText("OK");
        okBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okBtnActionPerformed(evt);
            }
        });

        cancelBtn.setText("Cancel");

        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("* Different from profile password");

        oldPassPF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                oldPassPFFocusLost(evt);
            }
        });

        oldPassLbl.setForeground(new java.awt.Color(255, 0, 0));

        confirmnPassLbl.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout passwordPnlLayout = new javax.swing.GroupLayout(passwordPnl);
        passwordPnl.setLayout(passwordPnlLayout);
        passwordPnlLayout.setHorizontalGroup(
            passwordPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(passwordPnlLayout.createSequentialGroup()
                .addGroup(passwordPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(passwordPnlLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(okBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cancelBtn))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, passwordPnlLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(passwordPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(passwordPnlLayout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(101, 101, 101))
                            .addGroup(passwordPnlLayout.createSequentialGroup()
                                .addGroup(passwordPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(confirmpassLbl)
                                    .addComponent(newpassLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(oldpassLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(passwordPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(oldPassPF)
                                    .addComponent(newPassTF)
                                    .addComponent(confPassTF))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(passwordPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(oldPassLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                    .addComponent(confirmnPassLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        passwordPnlLayout.setVerticalGroup(
            passwordPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(passwordPnlLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(passwordPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(oldPassLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(passwordPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(oldpassLbl)
                        .addComponent(oldPassPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24)
                .addGroup(passwordPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newpassLbl)
                    .addComponent(newPassTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(passwordPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(confirmnPassLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(passwordPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(confirmpassLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(confPassTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(36, 36, 36)
                .addComponent(jLabel5)
                .addGap(19, 19, 19)
                .addGroup(passwordPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(okBtn)
                    .addComponent(cancelBtn))
                .addGap(31, 31, 31))
        );

        productslbl.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        productslbl.setForeground(new java.awt.Color(0, 0, 153));
        productslbl.setText("Products And Services");

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(new java.awt.GridLayout(5, 2, 5, 5));

        billBtn1.setForeground(new java.awt.Color(0, 0, 204));
        billBtn1.setText("Bill Payment");
        jPanel3.add(billBtn1);

        accountBtn1.setForeground(new java.awt.Color(0, 0, 204));
        accountBtn1.setText("Open Account");
        accountBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountBtn1ActionPerformed(evt);
            }
        });
        jPanel3.add(accountBtn1);

        fundsBtn1.setForeground(new java.awt.Color(0, 0, 204));
        fundsBtn1.setText("Transfer Funds");
        jPanel3.add(fundsBtn1);

        accounttransBtn1.setForeground(new java.awt.Color(0, 0, 204));
        accounttransBtn1.setText("View Account Transactions");
        jPanel3.add(accounttransBtn1);

        chequeBtn1.setForeground(new java.awt.Color(0, 0, 204));
        chequeBtn1.setText("Cheque Services");
        jPanel3.add(chequeBtn1);

        loansBtn1.setForeground(new java.awt.Color(0, 0, 204));
        loansBtn1.setText("Loans");
        jPanel3.add(loansBtn1);

        fdBtn1.setForeground(new java.awt.Color(0, 0, 204));
        fdBtn1.setText("Fixed Deposits");
        jPanel3.add(fdBtn1);

        balanceBtn1.setForeground(new java.awt.Color(0, 0, 204));
        balanceBtn1.setText("Balance Enquiry");
        jPanel3.add(balanceBtn1);

        closeaccountBtn1.setForeground(new java.awt.Color(0, 0, 204));
        closeaccountBtn1.setText("Close Account");
        jPanel3.add(closeaccountBtn1);

        utilitiesBtn1.setForeground(new java.awt.Color(0, 0, 204));
        utilitiesBtn1.setText("Utilities");
        jPanel3.add(utilitiesBtn1);

        javax.swing.GroupLayout productPnlLayout = new javax.swing.GroupLayout(productPnl);
        productPnl.setLayout(productPnlLayout);
        productPnlLayout.setHorizontalGroup(
            productPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(productPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(productPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 432, Short.MAX_VALUE)
                    .addGroup(productPnlLayout.createSequentialGroup()
                        .addComponent(productslbl, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        productPnlLayout.setVerticalGroup(
            productPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(productPnlLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(productslbl, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE)
                .addContainerGap())
        );

        profilePnl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setText("<html><body>Name<font color=\"red\"> *</font></body></html>");

        jLabel4.setText("Address");

        jLabel6.setText("City");

        jLabel7.setText("Postal Code");

        jLabel8.setText("Country");

        jLabel9.setText("Home Phone Number");

        jLabel10.setText("Work Phone NUmber");

        jLabel11.setText("Mobile Phone NUmber");

        displayImgLbl.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        changePicLbl.setText("Change Picture");
        changePicLbl.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        changePicLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                changePicLblMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout profilePnlLayout = new javax.swing.GroupLayout(profilePnl);
        profilePnl.setLayout(profilePnlLayout);
        profilePnlLayout.setHorizontalGroup(
            profilePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profilePnlLayout.createSequentialGroup()
                .addGroup(profilePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(profilePnlLayout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(homephoneTF, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(profilePnlLayout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(workphoneTF, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(profilePnlLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(nameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(profilePnlLayout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(addressTF, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(profilePnlLayout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(cityTF, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(profilePnlLayout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(postalTF, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(profilePnlLayout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(countryTF, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(profilePnlLayout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(mobileTF, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(profilePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(profilePnlLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(displayImgLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(profilePnlLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(changePicLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        profilePnlLayout.setVerticalGroup(
            profilePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profilePnlLayout.createSequentialGroup()
                .addGroup(profilePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(profilePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addressTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(profilePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cityTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(profilePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(postalTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(profilePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(countryTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(profilePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(homephoneTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(profilePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(workphoneTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(profilePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mobileTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, profilePnlLayout.createSequentialGroup()
                .addComponent(displayImgLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(changePicLbl)
                .addGap(27, 27, 27))
        );

        jLabel12.setForeground(new java.awt.Color(255, 0, 51));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("* Required Fields");

        submitBtn.setText("Submit");
        submitBtn.setToolTipText("Submit");
        submitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBtnActionPerformed(evt);
            }
        });

        clearBtn.setText("Clear");
        clearBtn.setToolTipText("Clear");
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });

        emailLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        emailLbl.setText("<html><body> E-mai :   : <font color=\"red\">This cannot be updated</font></body></html>");

        emailTF.setEditable(false);

        javax.swing.GroupLayout profileuserPnlLayout = new javax.swing.GroupLayout(profileuserPnl);
        profileuserPnl.setLayout(profileuserPnlLayout);
        profileuserPnlLayout.setHorizontalGroup(
            profileuserPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profileuserPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(profileuserPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(profileuserPnlLayout.createSequentialGroup()
                        .addComponent(profilePnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(profileuserPnlLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(submitBtn)
                        .addGap(18, 18, 18)
                        .addComponent(clearBtn)
                        .addGap(76, 76, 76))
                    .addGroup(profileuserPnlLayout.createSequentialGroup()
                        .addComponent(emailLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(emailTF, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        profileuserPnlLayout.setVerticalGroup(
            profileuserPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profileuserPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(profilePnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(profileuserPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(profileuserPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(profileuserPnlLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 2, Short.MAX_VALUE)
                        .addGroup(profileuserPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(clearBtn)
                            .addComponent(submitBtn))
                        .addContainerGap())
                    .addGroup(profileuserPnlLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel12)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        SessionTable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Username", "Serial No", "Login", "LogOut"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout SessionTableLayout = new javax.swing.GroupLayout(SessionTable);
        SessionTable.setLayout(SessionTableLayout);
        SessionTableLayout.setHorizontalGroup(
            SessionTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SessionTableLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        SessionTableLayout.setVerticalGroup(
            SessionTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SessionTableLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE)
                .addContainerGap())
        );

        accProfile.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 204, 153));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Account Profile Management");

        jLabel14.setText("Account Number");

        jLabel15.setText("Account Branch");

        accBranchTF.setEditable(false);
        accBranchTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accBranchTFActionPerformed(evt);
            }
        });

        jLabel16.setText("Account Type");

        accTypeTF.setEditable(false);
        accTypeTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accTypeTFActionPerformed(evt);
            }
        });

        jLabel18.setText("Description");

        descriptionTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                descriptionTFKeyPressed(evt);
            }
        });

        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        cancelBtn1.setText("Cancel");

        jLabel19.setText("Press Enter to Update");

        addAccBtn.setText("Add New Account");
        addAccBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAccBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout accProfileLayout = new javax.swing.GroupLayout(accProfile);
        accProfile.setLayout(accProfileLayout);
        accProfileLayout.setHorizontalGroup(
            accProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accProfileLayout.createSequentialGroup()
                .addGroup(accProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(accProfileLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(accProfileLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(accProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(accProfileLayout.createSequentialGroup()
                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(addAccBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cancelBtn1))
                            .addGroup(accProfileLayout.createSequentialGroup()
                                .addGroup(accProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(accProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(accBranchTF)
                                    .addComponent(accTypeTF)
                                    .addComponent(descriptionTF, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                                    .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        accProfileLayout.setVerticalGroup(
            accProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accProfileLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addGroup(accProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(accProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(accBranchTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(accProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(accTypeTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(accProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(descriptionTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(accProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelBtn1)
                    .addComponent(jLabel19)
                    .addComponent(addAccBtn))
                .addGap(26, 26, 26))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSplitPane1.setDividerLocation(140);

        jButton1.setText("Change Password");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        profileupdateBtn.setText("Profile Update");
        profileupdateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profileupdateBtnActionPerformed(evt);
            }
        });

        jButton3.setText("Account Management");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        SessionBtn.setText("Session Log");
        SessionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SessionBtnActionPerformed(evt);
            }
        });

        productBtn.setText("Producst and Services");
        productBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(productBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(SessionBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(profileupdateBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(profileupdateBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SessionBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 124, Short.MAX_VALUE)
                .addComponent(productBtn)
                .addContainerGap())
        );

        jSplitPane1.setLeftComponent(jPanel1);

        jPanel2.setPreferredSize(new java.awt.Dimension(459, 214));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 292, Short.MAX_VALUE)
        );

        jSplitPane1.setRightComponent(jPanel2);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("UTILITIES");

        jButton2.setText("Help");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton5.setText("LogOut");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        welcomeTF.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        welcomeTF.setForeground(new java.awt.Color(255, 153, 153));
        welcomeTF.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        welcomeTF.setText("ggg");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(welcomeTF, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 675, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButton2)
                    .addComponent(jButton5)
                    .addComponent(welcomeTF, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSplitPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jSplitPane1.setRightComponent(passwordPnl);
        passwordPnl.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void profileupdateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profileupdateBtnActionPerformed
        jSplitPane1.setRightComponent(profileuserPnl);
        profileuserPnl.setVisible(true);
        try {
            Connection c1 = DBConnection.getConnection();
            String query1 = "select * from profile where username=?";
            try (PreparedStatement psmt1 = c1.prepareStatement(query1)) {
                psmt1.setString(1, user);
                try (ResultSet rs = psmt1.executeQuery()) {
                    if (rs.next()) {

                        {

                            nameTF.setText(rs.getString("name"));
                            addressTF.setText(rs.getString("address"));
                            cityTF.setText(rs.getString("city"));
                            postalTF.setText(rs.getString("postal_code"));
                            countryTF.setText(rs.getString("country"));
                            homephoneTF.setText(rs.getString("home_phone"));
                            workphoneTF.setText(rs.getString("work_phone"));
                            mobileTF.setText(rs.getString("mobile_phone"));
                            emailTF.setText(rs.getString("email"));

                            Blob b = rs.getBlob(9);//2 means 2nd column data  
                            byte barr[] = b.getBytes(1, (int) b.length());//1 means first image  

                            file = new File("e:\\abc.jpg");
                            FileOutputStream fout = new FileOutputStream(file);
                            fout.write(barr);
                            setPath(file);

                            fout.close();

                        }
                        //end of if  
                        System.out.println("ok");

                    }
                }

            }

        } catch (Exception ex) {
            ex.printStackTrace();
        }

    }//GEN-LAST:event_profileupdateBtnActionPerformed

    private void productBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productBtnActionPerformed
        this.dispose();
        new ProductList(user).setVisible(true);
    }//GEN-LAST:event_productBtnActionPerformed

    private void accountBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountBtn1ActionPerformed
        // this.dispose();
        // new UserRegistration(this).setVisible(true);
    }//GEN-LAST:event_accountBtn1ActionPerformed

    private void submitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBtnActionPerformed
        try {
            if (nameTF.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "enter name", "about name", JOptionPane.INFORMATION_MESSAGE);
                return;
            }

            Connection c2 = DBConnection.getConnection();
            String query = "update profile set name=?,address=?,city=?,postal_code=?,country=?,home_phone=?,work_phone=?,mobile_phone=?,image=? where username=?";

            PreparedStatement psmt = c2.prepareStatement(query);
            psmt.setString(1, nameTF.getText());
            psmt.setString(2, addressTF.getText());
            psmt.setString(3, cityTF.getText());
            psmt.setString(5, countryTF.getText());
            psmt.setString(4, postalTF.getText());
            psmt.setString(6, homephoneTF.getText());
            psmt.setString(7, workphoneTF.getText());
            psmt.setString(8, mobileTF.getText());
            FileInputStream fin = new FileInputStream(file);
            psmt.setBinaryStream(9, fin, fin.available());

            psmt.setString(10, user);

            int i = JOptionPane.showConfirmDialog(this, "Do you really want to update", "About Updation", JOptionPane.YES_NO_CANCEL_OPTION);

            if (i == 0) {

                if (psmt.executeUpdate() == 1) {

                    JOptionPane.showMessageDialog(this, "Successfully updated", "About Updation", JOptionPane.INFORMATION_MESSAGE);
                    nameTF.setText("");
                    addressTF.setText("");
                    cityTF.setText("");
                    postalTF.setText("");
                    homephoneTF.setText("");
                    countryTF.setText("");
                    workphoneTF.setText("");
                    mobileTF.setText("");
                    this.dispose();
                    new ProductList(user).setVisible(true);

                } else {
                    JOptionPane.showMessageDialog(this, "ERROR : ", "About Login", JOptionPane.ERROR_MESSAGE);
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_submitBtnActionPerformed

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        nameTF.setText("");
        addressTF.setText("");
        cityTF.setText("");
        postalTF.setText("");
        homephoneTF.setText("");
        countryTF.setText("");
        workphoneTF.setText("");
        mobileTF.setText("");
    }//GEN-LAST:event_clearBtnActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
        new Help(this, user).setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try {
            Connection c1 = DBConnection.getConnection();
            String query = "update user_session set logout=sysdate where user_id=? and logout is null ";
            PreparedStatement psmt1 = c1.prepareStatement(query);

            psmt1.setString(1, user);

            psmt1.executeUpdate();
            JOptionPane.showMessageDialog(this, "Successfully logout", "About logout", JOptionPane.INFORMATION_MESSAGE);

        } catch (Exception ex) {
            ex.printStackTrace();
        }
        this.dispose();
        new CoverFrame().setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void SessionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SessionBtnActionPerformed

        try {
            Connection con = DBConnection.getConnection();
            String query = "select * from user_session where user_id=?";
            PreparedStatement psmt = con.prepareStatement(query);
            psmt.setString(1, user);
            ResultSet rs = psmt.executeQuery();
            ResultSetMetaData rsmd;
            rsmd = rs.getMetaData();
            Vector column = new Vector();
            int count = rsmd.getColumnCount();
            DefaultTableModel dtm = new DefaultTableModel();
            for (int i = 1; i <= count; i++) {
                column.addElement(rsmd.getColumnName(i));
            }
            dtm.setColumnIdentifiers(column);
            while (rs.next()) {
                Vector row = new Vector();
                for (int i = 1; i <= count; i++) {
                    row.addElement(rs.getString(i));
                }
                dtm.addRow(row);
            }
            jTable1.setModel(dtm);
        } catch (Exception ex) {
            ex.printStackTrace();
        }

        jSplitPane1.setRightComponent(SessionTable);
        SessionTable.setVisible(true);
    }//GEN-LAST:event_SessionBtnActionPerformed

    private void accTypeTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accTypeTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_accTypeTFActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        //  jSplitPane1.setRightComponent(new NewJPanel());
        // new NewJPanel().setVisible(true);
        try {
            Connection con = DBConnection.getConnection();
            String query = "select account_no from user_account where user_id=?";
            PreparedStatement psmt = con.prepareStatement(query);
            psmt.setString(1, user);
            ResultSet rs = psmt.executeQuery();

            DefaultComboBoxModel model = (DefaultComboBoxModel) jComboBox2.getModel();
            while (rs.next()) {
                model.addElement(rs.getString("account_no"));
            }
            jComboBox2.setModel(model);
            rs.close();
            psmt.close();

        } catch (Exception ex) {
            ex.printStackTrace();
        }

        jSplitPane1.setRightComponent(accProfile);
        accProfile.setVisible(true);

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        try {
            String sql = "select * from user_account where account_no = '" + jComboBox2.getSelectedItem().toString() + "' ";
            Connection con = DBConnection.getConnection();

            Statement stm = con.createStatement();
            ResultSet rs = stm.executeQuery(sql);

            if (rs.next()) {
                accBranchTF.setText(rs.getString("account_branch"));
                accTypeTF.setText(rs.getString("account_type"));
                descriptionTF.setText(rs.getString("description"));
                descript = rs.getString("description");

            }

            rs.close();
            stm.close();

        } catch (Exception e) {
            e.printStackTrace();
        }


    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void accBranchTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accBranchTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_accBranchTFActionPerformed

    private void descriptionTFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_descriptionTFKeyPressed
        if (evt.getKeyCode() == 10) {
            int i = JOptionPane.showConfirmDialog(this, "Do you want to update", "About Account MAnagement", JOptionPane.YES_NO_CANCEL_OPTION);
            if (i == 0) {
                try {
                    Connection c3 = DBConnection.getConnection();
                    String query = "update user_account set description=? where account_no=? and user_id=?";
                    PreparedStatement psmt = c3.prepareStatement(query);
                    psmt.setString(1, descriptionTF.getText());
                    psmt.setString(2, jComboBox2.getSelectedItem().toString());
                    psmt.setString(3, user);
                    psmt.executeUpdate();
                    JOptionPane.showMessageDialog(this, "Updated", "About Description", JOptionPane.INFORMATION_MESSAGE);
                } catch (Exception ex) {
                    ex.printStackTrace();
                }

            } else {
                JOptionPane.showMessageDialog(this, "Not Updated", "About Description", JOptionPane.INFORMATION_MESSAGE);
                descriptionTF.setText(descript);
            }
        }
    }//GEN-LAST:event_descriptionTFKeyPressed

    private void changePicLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changePicLblMouseClicked

        try {
            int result = jFileChooser1.showOpenDialog(this);
            if (result == JFileChooser.APPROVE_OPTION) {
                file = jFileChooser1.getSelectedFile();
                setPath(file);

            }
        } catch (Exception e) {
            e.printStackTrace();
        }


    }//GEN-LAST:event_changePicLblMouseClicked

    private void oldPassPFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_oldPassPFFocusLost
        try {
            Connection c4 = DBConnection.getConnection();
            String query4 = "select * from profile_id where user_id=?";
            PreparedStatement psmt4 = c4.prepareStatement(query4);
            psmt4.setString(1, user);
            ResultSet rs = psmt4.executeQuery();
            if (rs.next()) {
                if (oldPassPF.getText().equals(rs.getString("lpass")) == false) {
                    oldPassLbl.setText("Password Is Not Correct");

                } else {
                    oldPassLbl.setText("");
                }
            }

        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_oldPassPFFocusLost

    private void okBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okBtnActionPerformed

        if (newPassTF.getText().equals(confPassTF.getText()) == false) {
            JOptionPane.showMessageDialog(this, "Passwords Do Not Match", "About Password", JOptionPane.INFORMATION_MESSAGE);
            return;
        } else {

            try {
                Connection co = DBConnection.getConnection();
                String sql = "update profile_id set lpass=?";
                PreparedStatement pst = co.prepareStatement(sql);
                pst.setString(1, confPassTF.getText());
                pst.executeUpdate();
                JOptionPane.showMessageDialog(this, "Updated Successfully", "About Updation", JOptionPane.INFORMATION_MESSAGE);
                pst.close();

            } catch (Exception e) {
                e.printStackTrace();
            }
        }

    }//GEN-LAST:event_okBtnActionPerformed

    private void addAccBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAccBtnActionPerformed
        this.dispose();
        new AddAccount().setVisible(true);
    }//GEN-LAST:event_addAccBtnActionPerformed

    private void setPath(File file) {
        try {
            //System.out.println(displayImgLbl.getSize());
            displayImgLbl.setSize(135, 143);
            ImageIcon icon = ResizeImage.scaleTo(file, displayImgLbl.getSize());

            if (icon != null) {
                displayImgLbl.setText("");
                displayImgLbl.setIcon(icon);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Utilities.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Utilities.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Utilities.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Utilities.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Utilities().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SessionBtn;
    private javax.swing.JPanel SessionTable;
    private javax.swing.JTextField accBranchTF;
    private javax.swing.JPanel accProfile;
    private javax.swing.JTextField accTypeTF;
    private javax.swing.JButton accountBtn1;
    private javax.swing.JButton accounttransBtn1;
    private javax.swing.JButton addAccBtn;
    private javax.swing.JTextField addressTF;
    private javax.swing.JButton balanceBtn1;
    private javax.swing.JButton billBtn1;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JButton cancelBtn1;
    private javax.swing.JLabel changePicLbl;
    private javax.swing.JButton chequeBtn1;
    private javax.swing.JTextField cityTF;
    private javax.swing.JButton clearBtn;
    private javax.swing.JButton closeaccountBtn1;
    private javax.swing.JPasswordField confPassTF;
    private javax.swing.JLabel confirmnPassLbl;
    private javax.swing.JLabel confirmpassLbl;
    private javax.swing.JTextField countryTF;
    private javax.swing.JTextField descriptionTF;
    private javax.swing.JLabel displayImgLbl;
    private javax.swing.JLabel emailLbl;
    private javax.swing.JTextField emailTF;
    private javax.swing.JButton fdBtn1;
    private javax.swing.JButton fundsBtn1;
    private javax.swing.JTextField homephoneTF;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton loansBtn1;
    private javax.swing.JTextField mobileTF;
    private javax.swing.JTextField nameTF;
    private javax.swing.JPasswordField newPassTF;
    private javax.swing.JLabel newpassLbl;
    private javax.swing.JButton okBtn;
    private javax.swing.JLabel oldPassLbl;
    private javax.swing.JPasswordField oldPassPF;
    private javax.swing.JLabel oldpassLbl;
    private javax.swing.JPanel passwordPnl;
    private javax.swing.JTextField postalTF;
    private javax.swing.JButton productBtn;
    private javax.swing.JPanel productPnl;
    private javax.swing.JLabel productslbl;
    private javax.swing.JPanel profilePnl;
    private javax.swing.JButton profileupdateBtn;
    private javax.swing.JPanel profileuserPnl;
    private javax.swing.JButton submitBtn;
    private javax.swing.JButton utilitiesBtn1;
    private javax.swing.JLabel welcomeTF;
    private javax.swing.JTextField workphoneTF;
    // End of variables declaration//GEN-END:variables
}
